### ISSUE TITLE
Missing javax/servlet/DispatcherType in case-study-ps.jar

### ISSUE THREAD

**Issue by theflofly** [trivago/junior-java-software-engineer-casestudy#1]
Hello,

I don't know if it is intentional or not, but the case-study-ps.jar misses servlet-api classes.

The result when running the jar will be a `Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/DispatcherType` exception.

It is possible to bypass the problem by downloading the jar [https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api/3.0.1](here), putting it in a lib dir and adding it to the classpath when running case-study-ps.jar using the following command: `java -cp "case-study-ps.jar:libs/*" com.trivago.case_study_ps.CaseStudyPSApplication server`.

If it is unintentional, you should update the jar in the repo.

Regards.

**Comment by krafti4tw** [comment]
Thanks for letting us know. Seems like the archive was broken. It's fixed.
